config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :prod_negs
  end



  resources :single_bids


  resources :prod_negs do
    resources :single_bids
  end

  resources :users do
    resources :products do
      get :toggle_accept_offer
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
  has_many :prod_negs
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
  end

  def create
  end

  def update
  end

  def destroy
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-12" "products-container">
    <h1> Welcome: <%= current_user.first_name %></h1>
    <hr>
    <h2> These are your products for sale: </h2>
  </div>
  <div class="col-xs-12 products-container">
    <% current_user.products.each do |product| %>
      <% product.prod_negs.each do |pn| %>
        <div class="product-wrapper">
          <div class="product-image">
            <%= image_tag pn.product.image %>
          </div>
          <div class="product-description-wrapper">
            <h3><%= pn.product.title %></h3>
            <h4> Price: <%= pn.product.start_price %> </h4>
            <% if pn.product.accept_offers %>
              <%= link_to user_product_toggle_accept_offer_path(current_user.id, pn.product.id), :class => "btn btn-success btn-md", "data-toggle" => "modal", method: :put do %>Available for offers<% end %>
            <% else %>
              <%= link_to user_product_toggle_accept_offer_path(current_user.id, pn.product.id), :class => "btn btn-danger btn-md", "data-toggle" => "modal", method: :put do %>Unavailable for offers<% end %>
            <%end%>
            <% if  pn.single_bids.first != nil %>
              <%= link_to "Current Offer of #{pn.user.first_name}", prod_neg_path(pn.id), :class => "btn btn-success btn-md" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>