config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :prod_negs
  end



  resources :single_bids


  resources :prod_negs do
    resources :single_bids
  end

  resources :users do
    resources :products do
      get :toggle_accept_offer
    end
  end

end

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Product verkoop</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-8">
            <div class="product-show-top">

              <h4><%= @prod_neg.product.title %></h4>
              <h5><%= @prod_neg.product.product_type %></h5>
            </div>
            <div class="product-show-top">
              <h6>MAAT: <%= @prod_neg.product.size %></h6>
              <h6>OMSCHRIJVING:</h6>
              <p><%= @prod_neg.product.description %></p>
            </div>
            <div class="row">
              <div class="col-xs-8">
                <h3> Verkocht voor: €<%= @current_negotiation_bids.last.price %></h3>
              </div>
            </div>
          </div>
          <div class="col-xs-4">
            <div class="product-image">
              <%= image_tag @prod_neg.product.image %>
            </div>
          </div
      </div>
      <div class="modal-footer">
        <%= link_to "Finalize", product_path(@prod_neg.product.id, sold: true), class: "btn btn-success btn-md", method: :patch %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- _navbar.html.erb -->

<!-- Static navbar -->
<nav class="navbar navbar-fixed-top">
  <div class="navbar-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to image_tag("https://thenextcloset.com/assets/tnc_logo@2x-ab9d17d216a0c561fc53baa0702aa1ac.png"), root_path, class: "navbar-brand logo" %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">

          <% if !user_signed_in? %>
            <li><%= link_to "Log In", new_user_session_path, class: "nav-user" %></li>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-user" %></li>
          <% else %>
            <li class="dropdown">
              <a id="user_name_in_nav" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name + " " + current_user.last_name %> <span class="caret"></span></a>

              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
  <div class="navbar-bottom">
    <div class="container">
      <div class="navbar-header">
        <ul style="list-style: none; padding-left: 0">
          <li style="padding-left: 0"><%= link_to "JUST IN", root_path %></li>
          <li><%= link_to "SHOP", root_path %></li>
          <li><%= link_to "SALE", root_path %></li>
          <li><%= link_to "MERKEN", root_path %></li>
          <li><%= link_to "THE CLOSET OF", root_path %></li>
          <li><%= link_to "VERKOPEN", root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "YOUR CLOSET", users_path %></li>
            <li><%= link_to "NEGOTIATIONS", prod_negs_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_product_negotiation.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">NEGOTIATION AREA</div>

  <div class="panel-body">
    test 2
    <h2><%= @prod_neg.product.title %></h2>
    <%= image_tag @prod_neg.product.image %>
    <h4>Starting price: € <%= @prod_neg.product.start_price %>,00</h4>
    <p>Negotiation state: <%= @prod_neg.active == true ? "Active" : "Inactive" %></p>

    <h2>Offers and Counter offers</h2>
    <hr>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th></th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <!-- <% @prod_neg.single_bids.each do |bid| %>
          <% if bid != nil %>
            <% user_id = bid.user_id %>
            <% user = @users.select{|user| user[:id] == user_id} %>
            <tr>
              <td><%= bid.created_at %></td>
              <td><%= user.first_name %> sent offer</td>
              <td>€ <%= bid.price %></td>
            </tr>
        <% end %> -->
      </tbody>
    </table>

  </div>

</div>