config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :prod_negs
  end



  resources :single_bids


  resources :prod_negs do
    resources :single_bids
  end

  resources :users do
    resources :products do
      get :toggle_accept_offer
    end
  end

end

app/models/prod_neg.rb
class ProdNeg < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_many :single_bids

  def self.get_bids_from_current_negotiation(all_bids, params)

    select_bids = all_bids.select do |bid|
      bid.prod_neg_id == params[:id].to_i
    end

    return select_bids
  end

  def self.setup_profile
    debugger
  end
end

app/controllers/prod_negs_controller.rb
class ProdNegsController < ApplicationController
  before_action :set_prod_negs, only: [:new, :index]
  before_action :set_prod_neg, only: [:show, :update]
  before_action :set_single_bids, only: [:show]
  before_action :authorize_buyer_seller, only: [:show]
  before_action :buyer_and_seller,  only: [:show]
  before_action :end_time, only: [:show]

  def index
  end

  def show
    @current_negotiation_bids = ProdNeg.get_bids_from_current_negotiation(@single_bids, params).sort_by &:created_at
  end

  def new
    redirect_if_negotiation_already_exists
    redirect_if_product_accept_offer_is_false unless @already_redirected == true
    create_new_negotiation_and_redirect unless @already_redirected == true
  end

  def create
  end

  def update
    @prod_neg.update_attribute(:active, false)

    redirect_to prod_negs_path, alert: "Negotiation closed"
  end

  def destroy
  end

  private

    def set_prod_negs
      @prod_negs = ProdNeg.all
    end

    def set_prod_neg
      @prod_neg = ProdNeg.find(params[:id])
    end

    def set_single_bids
      @single_bids = SingleBid.all
    end

    def authorize_buyer_seller
      # if current_user id is equal to Product owner or Product bidder, ok to continue, otherwise not.
      redirect_to product_path, alert: "Sorry, you can't see other peoples negotiations" unless (current_user.id == @prod_neg.user.id) || (current_user.id == @prod_neg.product.user_id)
    end

    def redirect_if_negotiation_already_exists
      # redirect to negotiation if Buyer already has a negotiation for this product
      @already_redirected = false
      found_negotiation = current_user.prod_negs.find do |negotiation|
        negotiation.product_id == params[:format].to_i
      end
      redirect_to prod_neg_path(found_negotiation.id), alert: "You already have a negotiation for this product" unless found_negotiation == nil
      @already_redirected = true unless found_negotiation == nil
    end

    def redirect_if_product_accept_offer_is_false
      product_id = params[:format].to_i
      if (Product.find(product_id).accept_offers === false)
        redirect_to product_path(product_id), alert: "Sorry, the seller has set this product as not available for new biddings"
        @already_redirected = true
      end
    end

    def create_new_negotiation_and_redirect
      prod_neg = ProdNeg.new
      prod_neg.update_attributes(product_id: params[:format], user_id: current_user.id)
      prod_neg.save
      redirect_to prod_neg_path(prod_neg.id), notice: "Succesfully created a new negotiation"
    end

    def buyer_and_seller
      @buyer = User.find(@prod_neg.user.id)
      @seller = User.find(@prod_neg.product.user_id)
    end

    def end_time
      current_negotiation_bids = ProdNeg.get_bids_from_current_negotiation(@single_bids, params)
      if current_negotiation_bids.length != 0
        last_bid = current_negotiation_bids.last
        @end_time = last_bid.created_at + 2.days
      end
    end
end

app/views/prod_negs/index.html.erb
<div class="row">
  <div class="col-xs-12" class="products-container">
    <h1> Welcome: <%= current_user.first_name %></h1>
    <hr>
    <h2> For these products you have started a negotiation: </h2>
    <div class="col-xs-12 products-container">
      <% current_user.prod_negs.each do |prod_neg| %>
        <div class="product-wrapper">
          <div class="product-image">
            <%= link_to image_tag(prod_neg.product.image), prod_neg_path(prod_neg.id)  %>
          </div>
          <div class="product-description">
            <h3><%= prod_neg.product.title %></h3>
            <h4>Starting Price: <%= prod_neg.product.start_price %></h4>
            <% if prod_neg.single_bids.last != nil %>
              <h4>Last bid: <%= prod_neg.single_bids.last.price %> </h4>
            <% else %>
              <h4>No bidding done so far</h4>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/prod_negs/new.html.erb
<h1>New Productnegotiation</h1>

app/views/prod_negs/show.html.erb
<div class="row bottom-spacer">
  <div class="col-xs-8">
    <div class="product-show-top">
      <h2 class="bottom-spacer">NEGOTIATIONS with <%= @seller.first_name %> and <%= @buyer.first_name %></h2>
      <h4><%= @prod_neg.product.title %></h4>
      <h5><%= @prod_neg.product.product_type %></h5>
    </div>
    <div class="product-show-top">
      <h6>MAAT: <%= @prod_neg.product.size %></h6>
      <h6>OMSCHRIJVING:</h6>
      <p><%= @prod_neg.product.description %></p>
    </div>
    <div class="row">
      <div class="col-xs-2">
        <h4><del>€<%= @prod_neg.product.original_price %></del></h4>
      </div>
      <div class="col-xs-2">
        <h4>€<%= @prod_neg.product.start_price %></h4>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="product-image">
      <%= image_tag @prod_neg.product.image %>
    </div>
  </div>
</div>
<% if @current_negotiation_bids.length != 0 %>
  <% time_remaining = (@end_time - Time.now).to_i %>
<% else %>
  <% time_remaining = 1 %>
<% end %>
<% if !!!@prod_neg.active || time_remaining <= 0 %>
 <h3>This negotiation is closed</h3>
<% else %>
  <div class="row current-bid bottom-spacer">
    <% if @current_negotiation_bids.length != 0 %>
      <div class="col-xs-3">
        <div>
          <h3>Last Offer: €<%= @current_negotiation_bids.last.price %></h3>
          <h5>Time remaining: <%= time_remaining/3600 %>hr : <%= time_remaining / 60 % 60 %>min : <%= time_remaining % 60 %>sec</h5>
          </div>
      </div>

      <div class="col-xs-1">
        <% if current_user == @prod_neg.product.user %>
          <% if @current_negotiation_bids.last.accepted == true %>
            <button type="button" class="btn btn-success btn-md" data-toggle="modal" data-target="#myModal">
              Finalize
            </button>
          <% end %>
        <% end %>
      </div>
      <div class="col-xs-2">
        <%= link_to "Cancel Negotiation", prod_neg_path(@prod_neg.id), class: "btn btn-danger btn-md", method: :patch %>
      </div>
      <% if current_user.id != @current_negotiation_bids.last.user_id %>
        <div class="col-xs-1">
            <%= link_to "Accept", prod_neg_single_bid_path(@current_negotiation_bids.last.id, accepted: true), class: "btn btn-success btn-md", method: :patch %>
        </div>
        <% if !!!@current_negotiation_bids.last.accepted %>
          <%= form_tag prod_neg_single_bids_path(@prod_neg.id) do %>
            <div class="col-xs-2">
              <%= number_field_tag :price, 'quantity' %>
            </div>
            <div class="col-xs-2">
              <%= submit_tag "Counter Offer", class: "btn btn-danger btn-md" %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <h4>There are no bids yet</h4>
      <%= form_tag prod_neg_single_bids_path(@prod_neg.id) do %>
      <%= number_field_tag :price, 'quantity' %>
      <%= submit_tag "Make Offer", class: "btn btn-danger btn-md" %>
      <% end %>
    <% end %>
  </div>
  <% @current_negotiation_bids.each do |bid| %>
    <div class="row">
      <% if bid.user_id == current_user.id %>
        <div class="col-xs-1" style="text-align: center;">
          <img src="https://thenextcloset.com/assets/icons/default_user/thumb_default_profile-54c8835634e5e5f1a5f71d7c8c18a9fb.png">
          <% if current_user.id == @seller.id %><%= @seller.first_name %><% else %><%= @buyer.first_name %><% end %>
        </div>
        <div class="col-xs-8">
          <div class="callouts">
            <div class="callouts--left">
              <div class="row">
                <div class="col-xs-2">&nbsp;</div>
                <div class="col-xs-4">
                  <h3>€ <%= bid.price %></h3>
                </div>
                <div class="col-xs-3">&nbsp;</div>
                <div class="col-xs-3">
                  <sup><%= bid.created_at %></sup>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-3">&nbsp;</div>
      <% else %>
        <div class="col-xs-3">&nbsp;</div>
        <div class="col-xs-8">
          <div class="callouts">
            <div class="callouts--right">
              <div class="row">
                <div class="col-xs-3">
                  <sup><%= bid.created_at %></sup>
                </div>
                <div class="col-xs-6">&nbsp;</div>
                <div class="col-xs-3">
                  <h3>€ <%= bid.price %></h3>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-1" style="text-align: center;">
          <img src="https://thenextcloset.com/assets/icons/default_user/thumb_default_profile-54c8835634e5e5f1a5f71d7c8c18a9fb.png">
          <% if current_user.id == @seller.id %><%= @buyer.first_name %><% else %><%= @seller.first_name %><% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>


<%= render '/shared/modal' unless @current_negotiation_bids.last == nil %>