config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :prod_negs
  end



  resources :single_bids


  resources :prod_negs do
    resources :single_bids
  end

  resources :users do
    resources :products do
      get :toggle_accept_offer
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :prod_negs

  validates :title, presence: true, length: {maximum: 20}
  validates :start_price, presence: true
  validates :image, presence: true
  validates :description, presence: true, length: {maximum: 500}
  validates :size, presence: true

  def self.toggle_accept_offer_attribute
    debugger
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :update, :index]
  before_action :set_products, only: [:show]
  before_action :set_prod_neg, only: [:show]

  def index
  end

  def show
  end

  def create
  end

  def update
    if @product.update_attribute(:sold, true)
      @product.save
    end
     redirect_to root_path, notice: "Product Sold!"
  end

  def toggle_accept_offer
    product = Product.find(params[:product_id].to_i)
    change_accept_offer_boolean(product)
  end

  def destroy
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def set_products
        @products = Product.all
    end

    def set_prod_neg
        @prod_neg = @product.prod_negs.find do |pn|
        pn.user_id == current_user.id
      end
    end

    def change_accept_offer_boolean(product)
      new_state = !product.accept_offers
      product.update_attributes(accept_offers: new_state)
      product.save
      redirect_to users_path
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="row">
  <h3 style="text-align: center; font-size: 16px;">ONZE FAVORIETEN</h3>
  <div class="col-xs-12 products-container">
    <% @products.each do |product| %>
      <div class="product-wrapper">
        <div class="product-image">
          <%= link_to image_tag(product.image), product_path(product.id) %>
        </div>
        <div class="product-description-wrapper">
          <h5><%= link_to product.title, product_path(product.id) %></h5>
          <h6><%= link_to product.product_type, product_path(product.id)%></h6>

          <div class="pull-left"><%= product.size %></div>
          <div class="pull-right">
            <% if product.sold %>
              <h4>Verkocht!</h4>
            <% else %>
              <del>€<%= product.original_price %></del>
              €<%= product.start_price %>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <div class="product-image">
      <%= image_tag @product.image %>
    </div>
  </div>
  <div class="col-xs-6">
    <div class="product-show-top">
      <h4><%= @product.title %></h4>
      <h5><%= @product.product_type %></h5>
      <ul class="product-show-icons">
        <li><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>sinds 20-4</li>
        <li><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>115x bekeken</li>
        <li><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>4x op verlanglijstje</li>
        <li><span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span><%= @product.prod_negs.length %>x op geboden</li>
      </ul>
    </div>
    <div class="row">
      <div class="col-xs-8">
        <h5><del>€<%= @product.original_price %></del></h5><h4>€<%= @product.start_price %></h4>
        <hr>
        <% if current_user.id == @product.user_id %>
          This is your product
        <% elsif @product.accept_offers == true %>
          <%= link_to "IN SHOPPING BAG", product_path(@product.id), :class => "btn btn-danger btn-md" %>
          <%= link_to "DOE EEN BOD", new_prod_neg_path(@product), :class => "btn btn-danger btn-md", "data-toggle" => "modal" %>
        <% else %>
          <%= link_to "IN SHOPPING BAG", product_path(@product.id), :class => "btn btn-danger btn-md" %>
        <% end %>
        <hr>
        <h6>MAAT: <%= @product.size %></h6>
        <h6>OMSCHRIJVING:</h6>
        <p><%= @product.description %></p>
      <div>
    <div>

  </div>
</div>